# config/packages/nucleos_user.yaml
nucleos_user:
  db_driver: mongodb
  firewall_name: main
  user_class: App\Document\User
  group:
    group_class: App\Document\UserGroup
  from_email: "noreply@tudominio.com"
  loggedin:
    route: 'homepage'