security:
  password_hashers:
    Nucleos\UserBundle\Model\UserInterface: auto

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    nucleos_userbundle:
      id: nucleos_user.user_provider.username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt|fragment|error)|css|images|js)/
      security: false

    main:
      lazy: true
      pattern: ^/
      user_checker: Nucleos\UserBundle\Security\UserChecker
      form_login:
        provider: nucleos_userbundle
        enable_csrf: true
        success_handler: App\Security\Handler\LoginSuccessHandler
        failure_handler: App\Security\Handler\LoginFailureHandler
        use_referer: true

      logout: true
      access_denied_handler: App\Security\AccessDeniedHandler

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
