security:
  password_hashers:
    Nucleos\UserBundle\Model\UserInterface: auto

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    nucleos_userbundle:
      id: nucleos_user.user_provider.username

  firewalls:
    main:
      pattern: ^/
      form_login:
        provider: nucleos_userbundle
        enable_csrf: true
        success_handler: App\Security\Handler\LoginSuccessHandler
        failure_handler: App\Security\Handler\LoginFailureHandler

      logout: true
      access_denied_handler: App\Security\AccessDeniedHandler

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
