# config/routes/nucleos_user.yaml
nucleos_user_security:
  resource: "@NucleosUserBundle/Resources/config/routing/security.php"

nucleos_user_resetting:
  resource: "@NucleosUserBundle/Resources/config/routing/resetting.php"
  prefix: /resetting

nucleos_user_change_password:
  resource: "@NucleosUserBundle/Resources/config/routing/change_password.php"
  prefix: /change-password

nucleos_user_deletion:
  resource: "@NucleosUserBundle/Resources/config/routing/deletion.php"
  prefix: /deletion

nucleos_user_security_login:
  controller: App\Controller\LoginAction
  path: /login